/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utfpr.victor.projetopoo2.visao;

/**
 *
 * @author Victor Almeida
 */
public class cadastroServico extends javax.swing.JFrame {

    /**
     * Creates new form cadastroFun
     */
    public cadastroServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tTITULO = new javax.swing.JTextField();
        tDESCRICAO = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        bCADASTRAR = new javax.swing.JButton();
        TITULO = new javax.swing.JLabel();
        FUNDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tTITULO.setText("Titulo");
        tTITULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTITULOActionPerformed(evt);
            }
        });
        getContentPane().add(tTITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 220, -1));

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        areaTexto.setText("Descriçao...");
        tDESCRICAO.setViewportView(areaTexto);

        getContentPane().add(tDESCRICAO, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        bCADASTRAR.setBackground(new java.awt.Color(102, 255, 153));
        bCADASTRAR.setForeground(new java.awt.Color(102, 255, 153));
        bCADASTRAR.setText("Cadastrar");
        bCADASTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCADASTRARActionPerformed(evt);
            }
        });
        getContentPane().add(bCADASTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        TITULO.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        TITULO.setText("Cadastro Serviço");
        getContentPane().add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        FUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utfpr/victor/projetopoo2/visao/img/fundo.png"))); // NOI18N
        getContentPane().add(FUNDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tTITULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTITULOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTITULOActionPerformed

    private void bCADASTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCADASTRARActionPerformed
        
        
        
    }//GEN-LAST:event_bCADASTRARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FUNDO;
    private javax.swing.JLabel TITULO;
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton bCADASTRAR;
    private javax.swing.JScrollPane tDESCRICAO;
    private javax.swing.JTextField tTITULO;
    // End of variables declaration//GEN-END:variables
}
