/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utfpr.victor.projetopoo2.visao;

/**
 *
 * @author victo
 */
public class Tela_ADM extends javax.swing.JFrame {

    /**
     * Creates new form Tela_ADM
     */
    public Tela_ADM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCLIENTE = new javax.swing.JButton();
        jSERVICO = new javax.swing.JButton();
        jFUNCIONARIO = new javax.swing.JButton();
        bSAIR = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jCLIENTE.setText("Cliente");
        jCLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLIENTEActionPerformed(evt);
            }
        });

        jSERVICO.setText("Serviços");
        jSERVICO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSERVICOActionPerformed(evt);
            }
        });

        jFUNCIONARIO.setText("Funcionario");
        jFUNCIONARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFUNCIONARIOActionPerformed(evt);
            }
        });

        bSAIR.setText("Sair");
        bSAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSAIRActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSERVICO, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bSAIR, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jFUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFUNCIONARIO)
                    .addComponent(jCLIENTE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSERVICO)
                    .addComponent(bSAIR))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSERVICOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSERVICOActionPerformed
        
        
        
        
        Tela_Servico tela_servico = new Tela_Servico();
        tela_servico.setVisible(true);
        Tela_ADM view = new Tela_ADM();
        view.dispose();
        
    }//GEN-LAST:event_jSERVICOActionPerformed

    private void jFUNCIONARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFUNCIONARIOActionPerformed
        Tela_Funcionario tela_funcionario = new Tela_Funcionario();
        tela_funcionario.setVisible(true);
        Tela_ADM view = new Tela_ADM();
        view.dispose();
        
    }//GEN-LAST:event_jFUNCIONARIOActionPerformed

    private void jCLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLIENTEActionPerformed
        
        
        Tela_Cliente tela_cliente = new Tela_Cliente();
        tela_cliente.setVisible(true);
        Tela_ADM view = new Tela_ADM();
        view.dispose();
        
        
    }//GEN-LAST:event_jCLIENTEActionPerformed

    private void bSAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSAIRActionPerformed
        
        
        Tela_login tela_login = new Tela_login();
        tela_login.setVisible(true);
        
    }//GEN-LAST:event_bSAIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_ADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_ADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_ADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_ADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_ADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSAIR;
    private javax.swing.JButton jCLIENTE;
    private javax.swing.JButton jFUNCIONARIO;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jSERVICO;
    // End of variables declaration//GEN-END:variables
}
